
using IdentityServer4.Models;

namespace ShoppingCartCMC.STS.Models
{
    public class ErrorViewModel
    {
        //PW: generated by tempalte, not used
        //public string RequestId { get; set; }
        //public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public ErrorMessage Error { get; set; }
    }
}
